### ISSUE TITLE
在组件js里定义了两个proto对象

### ISSUE THREAD

**Issue by hellozhimin** [mqyqingfeng/Wheels#2]
在组件progress-indicator.js里定义了两个proto对象，看的有点不清楚，能不能分别定义两个不同的对象呢

**Comment by mqyqingfeng** [comment]
@hellozhimin 非常感谢指出哈~ 这个问题确实不该，我立刻去修改~

**Comment by mqyqingfeng** [comment]
@hellozhimin 已经修改啦，再次感谢~
